// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmv22gp0LRcd2EU2GoKoznt_H4dI-OMes',
    appId: '1:940323001846:web:83f40ecdcc09003351e3d7',
    messagingSenderId: '940323001846',
    projectId: 'ximena-hoyos-fit',
    authDomain: 'ximena-hoyos-fit.firebaseapp.com',
    storageBucket: 'ximena-hoyos-fit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnNIr2pcc_70r19Oz_ogakbRPgcNz1qY4',
    appId: '1:940323001846:android:8976a8536bfdfad551e3d7',
    messagingSenderId: '940323001846',
    projectId: 'ximena-hoyos-fit',
    storageBucket: 'ximena-hoyos-fit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvePb8qSemg9HFGpBPdkeiX7h591LVYJ4',
    appId: '1:940323001846:ios:7f8a62a09fceb36e51e3d7',
    messagingSenderId: '940323001846',
    projectId: 'ximena-hoyos-fit',
    storageBucket: 'ximena-hoyos-fit.appspot.com',
    androidClientId: '940323001846-1dv1bjnhcpt94m1dfg175f9hoo8hdsr1.apps.googleusercontent.com',
    iosClientId: '940323001846-7caeju4dke1cd4bjkb05g5b0ngb0u9gd.apps.googleusercontent.com',
    iosBundleId: 'com.apprunn.ximenaHoyosApp',
  );
}
